FROM argoexec-base

RUN apt-get update && \
    apt-get install -y curl jq procps git tar sudo && \
    rm -rf /var/lib/apt/lists/* && \
    curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /bin/

RUN adduser argoexec -u 800 --gid 0
RUN groupadd docker
RUN usermod -a -G docker argoexec

RUN echo 'argoexec ALL=(ALL) NOPASSWD: ALL' | sudo EDITOR='tee -a' visudo

COPY manifests/nonroot/exec.sh /bin/
RUN chmod +x /bin/exec.sh
COPY argoexec /usr/local/bin/
