#!/bin/bash
set -xe

id
printenv

#export KUBERNETES_SERVICE_HOST=kubernetes.default.svc.cluster.local
export KUBERNETES_SERVICE_PORT=443
echo $KUBERNETES_SERVICE_HOST

sudo env ARGO_POD_IP=$ARGO_POD_IP ARGO_POD_NAME=$ARGO_POD_NAME ARGO_NAMESPACE=$ARGO_NAMESPACE \
    KUBERNETES_SERVICE_PORT=$KUBERNETES_SERVICE_PORT KUBERNETES_SERVICE_HOST=$KUBERNETES_SERVICE_HOST \
    bash -c 'argoexec wait'